#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("android.Resource", IsApplication=true)]

namespace android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f030000
			public const int apptheme_color = 2130903040;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int apptheme_btn_check_off_disabled_focused_holo_dark = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int apptheme_btn_check_off_disabled_holo_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int apptheme_btn_check_off_focused_holo_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int apptheme_btn_check_off_holo_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int apptheme_btn_check_off_pressed_holo_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int apptheme_btn_check_on_disabled_focused_holo_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int apptheme_btn_check_on_disabled_holo_dark = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int apptheme_btn_check_on_focused_holo_dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int apptheme_btn_check_on_holo_dark = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int apptheme_btn_check_on_pressed_holo_dark = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int apptheme_btn_default_disabled_focused_holo_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int apptheme_btn_default_disabled_holo_dark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int apptheme_btn_default_focused_holo_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int apptheme_btn_default_normal_holo_dark = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int apptheme_btn_default_pressed_holo_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int apptheme_list_activated_holo = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int apptheme_list_focused_holo = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int apptheme_list_longpressed_holo = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int apptheme_list_pressed_holo_dark = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int apptheme_list_selector_disabled_holo_dark = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int apptheme_scrubber_control_disabled_holo = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int apptheme_scrubber_control_focused_holo = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int apptheme_scrubber_control_normal_holo = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int apptheme_scrubber_control_pressed_holo = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int apptheme_scrubber_primary_holo = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int apptheme_scrubber_secondary_holo = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int apptheme_scrubber_track_holo_dark = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int apptheme_text_select_handle_left = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int apptheme_text_select_handle_middle = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int apptheme_text_select_handle_right = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int apptheme_textfield_activated_holo_dark = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int apptheme_textfield_default_holo_dark = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int apptheme_textfield_disabled_focused_holo_dark = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int apptheme_textfield_disabled_holo_dark = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int apptheme_textfield_focused_holo_dark = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int demo = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int icon = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int jamme = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int jamme_activated_background = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int jamme_btn = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int jamme_checkbox = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int jamme_control = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int jamme_edit_text = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int jamme_progress = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int select_left = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int select_right = 2130837549;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050004
			public const int AppTheme = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int AutoCompleteTextViewAppTheme = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int ButtonAppTheme = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int ImageButtonAppTheme = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int SeekBarAppTheme = 2131034115;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
